### PR TITLE
Select design updates

### PR DESCRIPTION
**Pull request by rishichawda**
### Status :
Ready
##

### Description :

Update select design and minor bug fix.

##

### Related Issues :
#287 

##

## Todos
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Review by KRRISH96 — DISMISSED** [review]
LGTM

**Review by kaushiknishchay — CHANGES_REQUESTED** [review]
Increase the font size of the selected value


screenshot 2019-01-02 at 12 22 02 pm

**Comment by rishichawda** [comment]
@kaushiknishchay Update the font size.

**Review by kaushiknishchay — APPROVED** [review]

**Pull request merged**
