### PR TITLE
Slider component

### PR DESCRIPTION
**Pull request by rishichawda**

### CODE REVIEW

**Comment by rishichawda** [comment]
@KRRISH96 @prasanna1211 Can you please pull this branch and let me know if there are any bugs on the component.

**Comment by prasanna1211** [comment]
Looks cool, Will update the design in the weekend. Do we get a callback with values when we drop a slider. Also single slider is possible ?

**Comment by rishichawda** [comment]
> Looks cool, Will update the design in the weekend. Do we get a callback with values when we drop a slider. Also single slider is possible ?

Yes. We have a onChange callback for every update in value. Previously it was only on drop as you said, but with addition of tooltip ( for user accessibility, which I'm thinking about making optional ) the callback was changed to every change in value. And yes, you can use it as a single slider. 
https://github.com/Codebrahma/react-lite-ui/pull/110/commits/224ca5c536140e516778eddc928235110e6fb0ed commit is the complete single slider.

**Comment by rishichawda** [comment]
Currently we can also have option for the users to choose wether they want the callback on dropping or change events. Incase you think that should be added, let me know. I'll raise a PR with that too.

**Comment by prasanna1211** [comment]
@rishichawda I think the design update is not replicated. Will merge once it is updated.

**Comment by rishichawda** [comment]
@prasanna1211 Design updated.

**Pull request merged**
