### PR TITLE
Mixins

### PR DESCRIPTION
**Pull request by rishichawda**
Added a few mixins to demonstrate their possible use in making themes.

### CODE REVIEW

**Comment by prasanna1211** [comment]
@rishichawda will look at this tonight.

**Comment by rishichawda** [comment]
> @rishichawda will look at this tonight.

@prasanna1211 Only https://github.com/Codebrahma/react-lite-ui/pull/86/commits/2e023b50475cb01afee318abe8149df3fb05bb1c commit is relevant to this PR.

**Comment by prasanna1211** [comment]
@rishichawda this looks cool. Can we merge this ?

**Comment by rishichawda** [comment]
> @rishichawda this looks cool. Can we merge this ?

Can be merged. Incase anything breaks, I'll fix it.

**Comment by prasanna1211** [comment]
@rishichawda Fixed it, In future think of adding more mixins for browser prefixes.

**Pull request merged**
