### PR TITLE
test(src/menu): add tests for menu component

### PR DESCRIPTION
**Pull request by rishichawda**

### CODE REVIEW

**Comment by rishichawda** [comment]
Accessibility tests cannot be written for now since it requires checking certain component style rules like `display` property in this case to check if sub menu is shown to user on hovering, etc.

**Review by prasanna1211 — DISMISSED** [review]

**Comment by prasanna1211** [comment]
Can you fix the conflicts ?

**Comment by rishichawda** [comment]
Okay I'll resolve the conflicts.

> Can you fix the conflicts ?

I'll resolve conflicts and push.

**Comment by rishichawda** [comment]
> Can you fix the conflicts ?

Yes. I'll resolve and push.

**Comment by rishichawda** [comment]
@prasanna1211 resolved conflicts. Can be merged now.

**Pull request merged**
