### PR TITLE
Autocomplete issue - #1

### PR DESCRIPTION
**Pull request by rishichawda**
Solves issues mentioned in - https://github.com/Codebrahma/react-lite-ui/issues/1

### CODE REVIEW

**Comment by prasanna1211** [comment]
Everything is looking good, except there should be a vertical padding between the content and the border bottom for the input. Cursor looks to be blinking on top of the input

**Review by prasanna1211 — CHANGES_REQUESTED** [review]
Need to give padding as commented

**Comment by rishichawda** [comment]
@prasanna1211 will update.

**Comment by rishichawda** [comment]
@prasanna1211 Padding fixed. Please check and merge.

**Review by prasanna1211 — APPROVED** [review]

**Pull request merged**
