### PR TITLE
fix(carousel): add shadow on hover

### PR DESCRIPTION
**Pull request by rishichawda**
### Status :
Ready
##

### Description :

Add shadow to increase button visibility

##

### Related Issues :
#287 

## Todos
- [x] Tests
- [x] Documentation

### CODE REVIEW

**Review by kaushiknishchay — CHANGES_REQUESTED** [review]
- Increase the ::before ::after width to around 9%
- Implement Pause of Carousel when user hovers on an item

**Comment by rishichawda** [comment]
The tests are failing because of coverage threshold. I'll update the tests now. Meanwhile @kaushiknishchay and @KRRISH96 can review the code.

**Review by kaushiknishchay — DISMISSED** [review]

**Review by KRRISH96 — COMMENTED** [review]
The `pauseOnHover` seems ineffective after clicking one of next or prev buttons.

**Comment by rishichawda** [comment]
> The pauseOnHover seems ineffective after clicking one of next or prev buttons.

Fixed in https://github.com/Codebrahma/react-lite-ui/pull/308/commits/97f5c0fed65716667cb43cda6a0ace36fa9ecd9e

**Review by KRRISH96 — DISMISSED** [review]

**Review by KRRISH96 — APPROVED** [review]

**Pull request merged**
