### PR TITLE
Navbar fix

### PR DESCRIPTION
**Pull request by rishichawda**
The build will fail for this PR since netlify is currently deploying from `doc/public` directory which doesn't exist on this branch.

### CODE REVIEW

**Comment by rishichawda** [comment]
Can we merge this soon? Since the navbar in landing page needs this. @prasanna1211 @KRRISH96

**Review by KRRISH96 — APPROVED** [review]

**Comment by KRRISH96** [comment]
How about we merge to `site` branch instead of development?
Since all the changes we need are with respect to new design.

**Comment by rishichawda** [comment]
> How about we merge to `site` branch instead of development?

Seems right. We can view changes on deploy previews that way.

**Comment by rishichawda** [comment]
Merging this PR now. @prasanna1211 @KRRISH96

**Pull request merged**
